
package eshop_server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service_Interface", targetNamespace = "http://eshop_Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceInterface {


    /**
     * 
     * @return
     *     returns java.util.List<eshop_server.ProductImplementation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllProductsResponse")
    @Action(input = "http://eshop_Server/Service_Interface/getAllProductsRequest", output = "http://eshop_Server/Service_Interface/getAllProductsResponse")
    public List<ProductImplementation> getAllProducts();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddOrderResponse")
    @Action(input = "http://eshop_Server/Service_Interface/addOrderRequest", output = "http://eshop_Server/Service_Interface/addOrderResponse")
    public void addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderImplementation arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns eshop_server.OrderImplementation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderbyID", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetOrderbyID")
    @ResponseWrapper(localName = "getOrderbyIDResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetOrderbyIDResponse")
    @Action(input = "http://eshop_Server/Service_Interface/getOrderbyIDRequest", output = "http://eshop_Server/Service_Interface/getOrderbyIDResponse")
    public OrderImplementation getOrderbyID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<eshop_server.OrderImplementation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllOrdersResponse")
    @Action(input = "http://eshop_Server/Service_Interface/getAllOrdersRequest", output = "http://eshop_Server/Service_Interface/getAllOrdersResponse")
    public List<OrderImplementation> getAllOrders();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddCustomerResponse")
    @Action(input = "http://eshop_Server/Service_Interface/addCustomerRequest", output = "http://eshop_Server/Service_Interface/addCustomerResponse")
    public void addCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        CustomerImplementation arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.AddProductResponse")
    @Action(input = "http://eshop_Server/Service_Interface/addProductRequest", output = "http://eshop_Server/Service_Interface/addProductResponse")
    public void addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        ProductImplementation arg0);

    /**
     * 
     * @return
     *     returns java.util.List<eshop_server.CustomerImplementation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCustomers", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllCustomers")
    @ResponseWrapper(localName = "getAllCustomersResponse", targetNamespace = "http://eshop_Server/", className = "eshop_server.GetAllCustomersResponse")
    @Action(input = "http://eshop_Server/Service_Interface/getAllCustomersRequest", output = "http://eshop_Server/Service_Interface/getAllCustomersResponse")
    public List<CustomerImplementation> getAllCustomers();

}
