
package eshop_server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service_ImplementationService", targetNamespace = "http://eshop_Server/", wsdlLocation = "http://localhost:8080/EShoppingService?wsdl")
public class ServiceImplementationService
    extends Service
{

    private final static URL SERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName SERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://eshop_Server/", "Service_ImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EShoppingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        SERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public ServiceImplementationService() {
        super(__getWsdlLocation(), SERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public ServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public ServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "Service_ImplementationPort")
    public ServiceInterface getServiceImplementationPort() {
        return super.getPort(new QName("http://eshop_Server/", "Service_ImplementationPort"), ServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "Service_ImplementationPort")
    public ServiceInterface getServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eshop_Server/", "Service_ImplementationPort"), ServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw SERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return SERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
